### ISSUE TITLE
Lacking test models for animated things

### ISSUE THREAD

**Issue by fire** [assimp/assimp-mdb#1]
Looking for samples with skeletons. Also 4 or 8 bone influences.

**Comment by kimkulling** [comment]
Good point, need to fix that.

**Comment by fire** [comment]
For example fbx, there are so many ways to break interpretation:

* scaled meshes
* fbx with pivots
* fbx without pivots
* 8 bone influences
* mesh with visibility set to 0

**Comment by fire** [comment]
More:
* root bone animation scaled to 100
* meter scaling of the scene

**Comment by fire** [comment]
IMVU Inc. has agreed to release some of our FBX based test models under the MIT license.

What is the process for that?
