### ISSUE TITLE
Bad model: box.3mf

### ISSUE THREAD

**Issue by ts-stevem** [assimp/assimp-mdb#6]
Assimp fails to load model `assimp-mdb/model-db/3mf/box.3mf` with error 
```
Validation failed: Mesh contains no faces
```

**Comment by kimkulling** [comment]
Ops, thanks for the hint. I will check!

**Comment by ts-stevem** [comment]
May also be reported as
```
Validation failed: A node of the scene-graph is nullptr
```

**Comment by tellypresence** [comment]
Just to confirm: the new model works perfectly, thank you!
