### ISSUE TITLE
Bad model: spider.3mf

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp-mdb#8]
Assimp fails to load model assimp-mdb/model-db/3mf/spider.3mf with error
```
Validation failed: A node of the scene-graph is nullptr
```

**Comment by kimkulling** [comment]
Höh? Which assimp-version did you try? I just validated the model with the latest master and it worked for me. Could you provide the platform, the version of assimp and the post-processing steps which were uses?

THanks and many thanks for your help. I really appreciate this!

**Comment by tellypresence** [comment]
Apologies for delay, app was built against https://github.com/assimp/assimp/commit/102d38071107017003dcf6874931bdf107e5c772 (22 Dec 2020)

I noticed some 3mf-issue-fixing PRs were merged since then, so will try again after rebuilding against latest assimp commit

**Comment by tellypresence** [comment]
Just checked with latest commit https://github.com/assimp/assimp/commit/c52e5c4da8c2c6bd86b478386f360f9398da4aeb (20 Jan 2021), same result

```
Validation failed: A node of the scene-graph is nullptr
```
(All the other models fine, it's just the .3mfs that are failing)

Note: load flags include pre-transform-vertices in case that helps

**Comment by kimkulling** [comment]
Ok, thanks for the update.
